### ISSUE TITLE
[FEAT-2] Create docker image

### ISSUE THREAD

**Issue by aaletov** [aaletov/dormyboba-core#6]
# Overview

Необходимо реализовать сборку docker образа для данного репо. Проект использует poetry для управления зависимостями (работает +- как npm). poetry позволяет собирать .whl по команде poetry build. Все параметры читаются в коде из файла config.yaml, расположенного в корне проекта. Нужно понять как собрать проект и передать конфиг

Формат конфига

```
dormyboba:
  domain: 127.0.0.1:8000
  postgres:
    user: 'postgres'
    password: '123456'
    host: 'postgresql'
    db: 'dormyboba'
  gc:
    defect_sheet_id: '<<<SHEET_ID>>>'
```
